# These are supported funding model platforms

# GitHub Sponsors
github: # [FutureSolutionDev]  # Not supported yet

# Patreon
patreon: # futuresolutionsdev  # Not supported yet

# Open Collective
open_collective: # deploy-center  # Not supported yet

# Ko-fi
ko_fi: # futuresolutionsdev  # Not supported yet

# Buy Me a Coffee
custom: # ['https://www.buymeacoffee.com/futuresolutionsdev']  # Not supported yet

# Custom links
custom:
  - https://futuresolutionsdev.com/#contact

Current contact methods:
- Email: licensing@futuresolutionsdev.com
- Website: https://futuresolutionsdev.com
- Phone: +20 106 901 7890
- WhatsApp: +20 106 901 7890
