# These are supported funding model platforms

# GitHub Sponsors
github: # [FutureSolutionDev]  # Not supported yet

# Patreon
patreon: # futuresolutionsdev  # Not supported yet

# Open Collective
open_collective: # deploy-center  # Not supported yet

# Ko-fi
ko_fi: # futuresolutionsdev  # Not supported yet


# Custom links
custom:
  - https://www.paypal.com/ncp/payment/9T8REJA5D7Z4U

Current contact methods:
- Email: licensing@futuresolutionsdev.com
- Website: https://futuresolutionsdev.com
- Phone: +20 106 901 7890
- WhatsApp: +20 106 901 7890
